name: Create LeetCode Daily Problem Issue

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"  # Runs daily at 9am VNT

jobs:
  create-daily-lc-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -U requests python-dotenv

      - name: Set environment variables
        run: |
          echo "GITHUB_REPOSITORY=${{ github.repository }}" >> $GITHUB_ENV
          echo "GITHUB_TOKEN=${{ secrets.LC_GH_TOKEN }}" >> $GITHUB_ENV

      - name: Run the script
        run: python lc_gh_issue_bot.py
